version: "3.8"

services:
  api-taller-dev:
    container_name: api-taller-dev
    restart: unless-stopped
    env_file: .env
    build:
      target: dev
      context: .
      args:
        - PORT=${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
      - "9229:9229"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules/
    networks:
      docker_mi-red:
        ipv4_address: 172.0.0.5
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024m"
        reservations:
          cpus: "0.25"
          memory: "256m"
networks:
  docker_mi-red:
    external: true
