services:
  api-taller-pro:
    container_name: api-taller-pro
    image: api-taller-pro
    build:
      target: production
      context: .
      args:
        - PORT=3000
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./dist:/dist
      - ./node_modules:/node_modules
    networks:
      red_bd:
        ipv4_address: 172.0.0.5
networks:
  red_bd:
    name: red_bd
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/24
