version: "3.8"

services:
  api-taller-pro:
    container_name: api-taller-pro
    image: api-taller-pro
    build:
      target: production
      context: .
      args:
        - PORT=3000
    ports:
      - "3000:3000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512m"
        reservations:
          cpus: "0.25"
          memory: "256m"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules/
    networks:
      red_bd:
        ipv4_address: 172.0.0.5
networks:
  red_bd:
    external: true
