version: "3.8"

services:
  api-taller-pro:
    container_name: api-taller-pro-${BRANCH_NAME}
    build:
      target: production
      context: .
      args:
        - PORT=3000
    ports:
      - "3000:3000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512m"
        reservations:
          cpus: "0.25"
          memory: "256m"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules/
    networks:
      docker_mi-red:
        ipv4_address: 172.0.0.5
networks:
  docker_mi-red:
    external: true
